---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.8.12
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-10pro
    driver:
      box: hieunb/windows10pro
      gui: true
    transport:
      username: vagrant
      password: vagrant

suites:
  - name: default
    run_list:
      - recipe[windows_reboot_weekly::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
